name: Validate release info

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, ready_for_review]

jobs:
  check-pr:
    permissions:
      contents: write
      issues: read
      pull-requests: read
    uses: imdevinc/imdevinc/.github/workflows/shared-validate-semver-tags.yaml@v1
